services:
    frontend:
        container_name: decompil.in-frontend
        image: bun-sveltekit-frontend
        build:
            context: .
            dockerfile: FrontendDockerfile
        ports:
            - "127.0.0.1:5000:3000"
        depends_on:
            - "backend"
    backend:
        container_name: decompil.in-backend
        image: bun-elysiajs-backend
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:3000:3000"
        depends_on:
            - "mysql"
    mysql:
        image: mysql:latest
        container_name: decompil.in-database
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sqldump:/sqldump
        ports:
            - "127.0.0.1:3306:3306"
        restart: unless-stopped
        env_file: ./.db.env

volumes:
    mysqldata: {}
